### ISSUE TITLE
Suggestion: count number of sms

### ISSUE THREAD

**Issue by RAPXT** [Webierta/call-counter#3]
Hi,

would it be possible to add support for counting the number of sent (and received) SMS?

There are still some (prepaid) sim contracts that have an limited amount of included SMS (e. g. 100/200 per month), so I think counting them would make sense.

As for data consumption we have an inbuilt function in android, which fulfills my needs. But maybe there are users on older android versions or there's another good reason for it?!

Thanks for reading. I'm very slow to respond, so do not wonder, it could take weeks or even months for me to respond.

**Comment by Webierta** [comment]
Hi, thanks for the suggestions.

I do not rule out adding the function to count SMS in the future, although I did not start it because most of the companies I know do not offer any SMS plan.

Regarding the data consumption, I have not added it because, as you say, most Android systems incorporate this function as standard.

**Comment by L--U--P--U--S** [comment]
At least in Germany, it is quite usual for the (rather cheap) contracts to offer, e.g., 100 minutes per month, which is shared between actual outgoing calls and outgoing messages (one SMS equals one minute). I'm interested in this feature, too.

**Comment by Webierta** [comment]
Hello, I have just released version 2.0.0 (pending to be published on F-Droid) that adds the function of counting SMS messages.

I will be making minor changes to optimize the code shortly, so suggestions and error notices are appreciated.

**Comment by Webierta** [comment]
Version 2.0.0 published in F-Droid with reading SMS messages.
Version 2.0.1 released with minor bug fixes.

**Comment by lu-p-us** [comment]
I am still waiting for 2.0.1 to arrive on F-Droid, but I was able check out 2.0.0 already. The new SMS count feature seems to work perfectly … however, my personal understanding of this feature request was that calls and messages are counted against a **shared** balance and not being counted separately. I guess @Alex-Esko would agree on this. Not sure about @RAPXT, though.

Would this be an option to be implemented in a future release?

**Comment by Webierta** [comment]
I can think of that function if it really is a common practice in contracts. Is an SMS equivalent to 1 minute for all companies? (In Spain I do not know of any company that makes a shared balance of calls and SMS).

Forgive my slowness of thought (it must be due to the effect of the covid vaccine).
